backend:
  name: github
  repo: KushalThaman/physics 

media_folder: content/assets
public_folder: ../assets

collections:
  - name: physics
    label: Physics
    folder: content/physics
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
